# Redis数据源配置
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: ${smallboot.redis.database}
    # Redis服务器地址
    host: ${smallboot.redis.host}
    # Redis服务器连接端口
    port: ${smallboot.redis.port}
    timeout: 6000
    # Redis服务器连接密码（默认为空）
    password: ${smallboot.redis.password}
    jedis:
      pool:
        max-active: 100   # 连接池最大连接数（使用负值表示没有限制）  -- redis服务端最大连接数查看 `config get maxclients`；客户端单机最大连接数 * 集群数 不能超过服务端最大连接数
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
