# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)  注意不能带冒号:
  token-name: Authorization-smallboot
  # jwt秘钥
  jwt-secret-key: smallboot
  # token值前缀
  #  token-prefix: Bearer
  # token有效期，单位s 这里设置1天, -1代表永不过期
  timeout: 86400
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  # tips: 使用 jwt-simple 模式后，is-share=false 恒等于 false。
  is-share: false
  # token风格
  #  token-style: random-128
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从请求体里读取token
  is-read-body: false
  # 是否从head中读取token
  #  is-read-head: true
  # 是否输出操作日志
  is-log: true
  # 是否在初始化配置时打印版本字符画
  is-print: false
  # 拦截url
  intercept-url-list:
    - /**
  # 开放url
  open-url-list:
    # Knife4j
    - /webjars/**
    - /doc.html
    - /swagger-resources/**
    - /v2/api-docs
    - /v3/api-docs
    - /favicon.ico
    # 其它
    - /auth/**
